spring:
  profiles:
    active: dev
---
server:
  error:
    include-stacktrace: never
spring:
  profiles: dev
  datasource:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
    url: jdbc:postgresql://localhost:5432/octopusdb
    username: octopus
    password: changeme
    initialization-mode: always
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    show-sql: false

jwt:
  secret: octopus
  expiration: 86400000 # 24h = 24 * 60 * 60 * 1000

job:
  poolSize: 1

download:
  delay: 5000 #5s
  matchUrl: 'https://as.okooo.com/I/?method=mc.data.schedule.getOkoooSchedule&LotteryType=SportterySoccerMix&LotteryNo='

# spring cron job format
#1 2 3 4 5 6 Index
#- - - - - -
#* * * * * * command to be executed
#- - - - - -
#| | | | | |
#| | | | | ------- Day of week (MON - SUN)
#| | | | --------- Month (1 - 12)
#| | | ----------- Day of month (1 - 31)
#| |-------------- Hour (0 - 23)
#| --------------- Minute (0 - 59)
#----------------- Seconds (0 - 59)
scheduled:
  cron:
    downloadMatch: '* */1 * * * *'