spring:
  profiles:
    active: dev
---
server:
  error:
    include-stacktrace: never
spring:
  profiles: dev
  datasource:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
    url: jdbc:postgresql://localhost:5432/octopusdb
    username: octopus
    password: changeme
    initialization-mode: always
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: create-drop # change to `update` in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    show-sql: false

jwt:
  secret: octopus
  expiration: 86400000 # 24h = 24 * 60 * 60 * 1000

job:
  poolSize: 1

download:
  matchDate: '2020-05-07'
  delay: 5000 #5s
  matchUrl: 'https://as.okooo.com/I/?method=mc.data.schedule.getOkoooSchedule&LotteryType=SportterySoccerMix&LotteryNo=DATE_PLACEHOLDER'
  oddsUrl: 'https://as.okooo.com/I/?method=mc.data.odds.getOdds&SportId=1&MatchID=MATCH_ID_PLACEHOLDER'
  oddsChangeUrl: 'https://as.okooo.com/I/?method=mc.data.stat.getstat&SportId=1&MatchID=MATCH_ID_PLACEHOLDER&LId=PROVIDER_ID_PLACEHOLDER&bettingTypeId=1'

  handicapUrl: 'https://as.okooo.com/I/?method=mc.data.ah.getAh&SportId=1&MatchID=MATCH_ID_PLACEHOLDER'
  handicapChangeUrl: 'https://as.okooo.com/I/?method=mc.data.stat.getstat&SportId=1&MatchID=MATCH_ID_PLACEHOLDER&LId=PROVIDER_ID_PLACEHOLDER&bettingTypeId=2'

  oddsProviderIds:
    - 24 # 99Avg
    - 82 # Ladbrokes
    - 27 # Bet365

  handicapProviderIds:
    - 27 # Bet365
    - 43 # Interwetten
    - 35 # Easybets

# spring cron job format
# 1 2 3 4 5 6 Index
# - - - - - -
# * * * * * * command to be executed
# - - - - - -
# | | | | | |
# | | | | | ------- Day of week (MON - SUN)
# | | | | --------- Month (1 - 12)
# | | | ----------- Day of month (1 - 31)
# | |-------------- Hour (0 - 23)
# | --------------- Minute (0 - 59)
# ----------------- Seconds (0 - 59)
scheduled:
  cron:
    downloadMatch: '0 0/1 * * * *'
    updateMatch: '0/30 * * * * *'